version: "3.9"

networks:
  stock-ticker:
    driver: awsvpc

services:
  backend:
    build: ./server/.
    image: filipsannholm/stock-backend
    ports: 
      - 5000:5000
    restart: always
    environment:
      REDIS_HOST: 'redis://stock-ticker-redis-cluster.couksn.clustercfg.memorydb.eu-north-1.amazonaws.com'
      REDIS_PORT: 6379
    networks:
      - stock-ticker
  client:
    build: ./client/.
    image: filipsannholm/stock-frontend
    depends_on: 
      - backend
    ports:
      - 80:80
    networks:
      - stock-ticker
