version: "3.9"

services:
  redis:
    image: redis:latest
  backend:
    build: ./server/.
    ports: 
      - 5000:5000
    restart: always
    environment:
      REDIS_HOST: 'redis://redis'
      REDIS_PORT: 6379
    depends_on:
      - redis
  client:
    build: ./client/.
    depends_on: 
      - backend
    ports:
      - 80:80